name: build gravitron
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
    matrix:
    os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: install dependencies (clean-install)
      run: npm ci
    - name: build app, hopefully
      run: npm run make